/* empty css                      */import{a as L,S as w,i}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const S="33349547-44f128e159fc9ba4be7374396",q="https://pixabay.com/api/",d=15,P={key:S,q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15},$={query:"",totalHits:0,currentPage:0};async function f(n){const{query:r,page:o=1,limit:s=d}=n,e=new URLSearchParams({...P,q:r,page:o,per_page:s}),t=q+"?"+e.toString();return(await L.get(t)).data}let H=new w(".gallery a",{captionsData:"alt",captionDelay:250});const O=document.querySelector(".gallery");function E(n){const{webformatURL:r,largeImageURL:o,tags:s,likes:e,views:t,comments:a,downloads:l}=n;return`
        <div class="photo-card">
          <a href="${o}" target="_blank">
            <img src="${r}" alt="${s}" loading="lazy" />
          </a>
          <div class="info">
            <div class="info-item"><b>${e}</b>Likes</div>
            <div class="info-item"><b>${t}</b>Views</div>
            <div class="info-item"><b>${a}</b>Comments</div>
            <div class="info-item"><b>${l}</b>Downloads</div>
          </div>
        </div>`}function y(n){const r=n.map(o=>E(o)).join("");O.insertAdjacentHTML("beforeend",r),H.refresh()}const g=document.querySelector(".loader-container"),h=document.querySelector(".load-more-btn"),M=document.querySelector(".gallery"),_=document.querySelector("#searchForm");function p(){g.style.display="flex"}function b(){g.style.display="none"}function v(){h.style.display="block"}function u(){h.style.display="none"}function A(){M.innerHTML=""}function B(){_.search.value=""}const m=document.querySelector("#searchForm"),R=document.querySelector(".load-more-btn");let c={query:"",totalHits:0,currentPage:0};m.addEventListener("submit",async n=>{n.preventDefault();const r=m.search.value.trim();if(!r.length){i.info({message:"Search should not be empty!"});return}A(),u(),c={...$,query:r};try{p();const o=await f({query:r});if(!o.hits.length){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}c.totalHits=o.totalHits,c.currentPage+=1,B(),y(o.hits),o.totalHits>d&&v()}catch(o){i.error({message:`Oooops...Something went wrong... ${o.message}`}),u()}finally{b()}});R.addEventListener("click",async()=>{try{p(),u();const{query:n,currentPage:r,totalHits:o}=c,s=r*d;if(o-s<=0){i.warning({message:"We're sorry, but you've reached the end of search results."});return}const t=await f({query:n,page:r+1});c.currentPage+=1,y(t.hits);const a=document.querySelector(".photo-card");if(a){const l=a.getBoundingClientRect().height;window.scrollBy({top:l*2,behavior:"smooth"})}v()}catch(n){i.error({message:`Oooops...Something went wrong... ${n.message}`})}finally{b()}});
//# sourceMappingURL=index.js.map
