/* empty css                      */import{a as w,S,i}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const q="33349547-44f128e159fc9ba4be7374396",P="https://pixabay.com/api/",d=200,$={key:q,q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15},H={query:"",totalHits:0,currentPage:0};async function f(n){const{query:r,page:o=1,limit:s=d}=n,e=new URLSearchParams({...$,q:r,page:o,per_page:s}),t=P+"?"+e.toString();return(await w.get(t)).data}let O=new S(".gallery a",{captionsData:"alt",captionDelay:250});const E=document.querySelector(".gallery");function M(n){const{webformatURL:r,largeImageURL:o,tags:s,likes:e,views:t,comments:a,downloads:l}=n;return`
        <div class="photo-card">
          <a href="${o}" target="_blank">
            <img src="${r}" alt="${s}" loading="lazy" />
          </a>
          <div class="info">
            <div class="info-item"><b>${e}</b>Likes</div>
            <div class="info-item"><b>${t}</b>Views</div>
            <div class="info-item"><b>${a}</b>Comments</div>
            <div class="info-item"><b>${l}</b>Downloads</div>
          </div>
        </div>`}function y(n){const r=n.map(o=>M(o)).join("");E.insertAdjacentHTML("beforeend",r),O.refresh()}const g=document.querySelector(".loader-container"),h=document.querySelector(".load-more-btn"),_=document.querySelector(".gallery"),A=document.querySelector("#searchForm");function p(){g.style.display="flex"}function b(){g.style.display="none"}function v(){h.style.display="block"}function u(){h.style.display="none"}function B(){_.innerHTML=""}function R(){A.search.value=""}const m=document.querySelector("#searchForm"),x=document.querySelector(".load-more-btn");let c={query:"",totalHits:0,currentPage:0};m.addEventListener("submit",async n=>{n.preventDefault();const r=m.search.value.trim();if(!r.length){i.info({message:"Search should not be empty!"});return}B(),u(),c={...H,query:r};try{p();const o=await f({query:r});if(!o.hits.length){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}c.totalHits=o.totalHits,c.currentPage+=1,R(),y(o.hits),o.totalHits>d&&v()}catch(o){i.error({message:`Oooops...Something went wrong... ${o.message}`}),u()}finally{b()}});x.addEventListener("click",async()=>{try{p(),u();const{query:n,currentPage:r,totalHits:o}=c;let s=d;const e=r*s,t=o-e;if(t<=0){i.warning({message:"We're sorry, but you've reached the end of search results."}),u();return}t<s&&(s=t);const a=await f({query:n,page:r+1,limit:s});c.currentPage+=1,y(a.hits);const l=document.querySelector(".photo-card");if(l){const L=l.getBoundingClientRect().height;window.scrollBy({top:L*2,behavior:"smooth"})}v()}catch(n){i.error({message:`Oooops...Something went wrong... ${n.message}`})}finally{b()}});
//# sourceMappingURL=index.js.map
