/* empty css                      */import{a as b,S,i as l}from"./assets/vendor-BSTwZ_tR.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const v="33349547-44f128e159fc9ba4be7374396",w="https://pixabay.com/api/",g=15,L={key:v,q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15};async function f(s){const{query:o,page:t=1,limit:n=g}=s;await new Promise(c=>setTimeout(c,5e3));const e=new URLSearchParams({...L,q:o,page:t,per_page:n}),r=w+"?"+e.toString();return(await b.get(r)).data}let P=new S(".gallery a",{captionsData:"alt",captionDelay:250});const q=document.querySelector(".gallery");function O(s){const{webformatURL:o,largeImageURL:t,tags:n,likes:e,views:r,comments:a,downloads:c}=s;return`
        <div class="photo-card">
          <a href="${t}" target="_blank">
            <img src="${o}" alt="${n}" loading="lazy" />
          </a>
          <div class="info">
            <div class="info-item"><b>${e}</b>Likes</div>
            <div class="info-item"><b>${r}</b>Views</div>
            <div class="info-item"><b>${a}</b>Comments</div>
            <div class="info-item"><b>${c}</b>Downloads</div>
          </div>
        </div>`}function p(s){const o=s.map(t=>O(t)).join("");q.insertAdjacentHTML("beforeend",o),P.refresh()}const y=document.querySelector("#searchForm"),d=document.querySelector(".loader-container"),i=document.querySelector(".load-more-btn"),$=document.querySelector(".gallery"),u="queryParams";y.addEventListener("submit",async s=>{s.preventDefault(),localStorage.removeItem(u),$.innerHTML="",i.style.display="none";const o=y.search.value.trim();if(!o.length){l.info({message:"Search should not be empty!"});return}try{d.style.display="flex";const t=await f({query:o});if(!t.hits.length){l.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}localStorage.setItem(u,JSON.stringify({query:o,totalHits:t.totalHits,currentPage:1})),y.search.value="",p(t.hits),i.style.display="block"}catch(t){l.error({message:`Oooops...Something went wrong... ${t.message}`}),i.style.display="none"}finally{d.style.display="none"}});i.addEventListener("click",async()=>{try{d.style.display="flex",i.style.display="none";const s=JSON.parse(localStorage.getItem(u));if(!s||!Object.keys(s).length)return;const{query:o,currentPage:t,totalHits:n}=s;let e=g;const r=t*e,a=n-r;if(a<=0){l.warning({message:"We're sorry, but you've reached the end of search results."}),i.style.display="none";return}a<e&&(e=a);const c=await f({query:o,page:t+1,limit:e});localStorage.setItem(u,JSON.stringify({query:o,currentPage:t+1,totalHits:n})),p(c.hits);const m=document.querySelector(".photo-card");if(m){const h=m.getBoundingClientRect().height;window.scrollBy({top:h*2,behavior:"smooth"})}i.style.display="block"}catch(s){l.error({message:`Oooops...Something went wrong... ${s.message}`})}finally{d.style.display="none"}});
//# sourceMappingURL=index.js.map
